### ISSUE TITLE
从头开始训练是shell中的文件，但是trainer是用来做什么的，还有就是数据集没有MV_test1k吗，请求帮助

### ISSUE THREAD

**Issue by hqw666666** [ruc-aimc-lab/LAFF#4]

**Comment by fly-dragon211** [comment]
你好，trainer是用来训练的一个抽象类，数据集中有 MV_test1k，只需要按照https://github.com/ruc-aimc-lab/LAFF/tree/main/data 这里的格式，软连接一下就行
